name: Security Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        cd server
        go mod download
        
    - name: Run go vet
      run: |
        cd server
        go vet ./...
        
    - name: Run staticcheck
      run: |
        cd server
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
        
    - name: Run govulncheck
      run: |
        cd server
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
        
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Check for vulnerable dependencies
      run: |
        cd server
        go list -json -deps ./... | nancy sleuth
        
    - name: Update dependencies
      run: |
        cd server
        go get -u ./...
        go mod tidy
        
    - name: Test build
      run: |
        cd server
        go build -o websocket-server main.go
